### ISSUE TITLE
Force string output

### ISSUE THREAD

**Issue by efrecon** [dbohdan/jimhttp#4]
May I make the following suggestion? To be frank, I am not entirely satisfied with the solution, but it actually suits my current needs. You might want to take the idea further for refinement though...

I've had to find a way not to automatically convert things that integer or doubles to their JSON counterparts, i.e. a way to ensure that value 123 does not become the integer 123, but rather the string "123". To do this, I have slightly modified (see below) stringify to:
1. Take a new argument that requests string-only output
2. Recognises key that look like xxx!string as the key xxx which value should only be output as a string.

What do you think?

```
proc ::json::stringify {dictionaryOrValue {numberDictArrays 1} {allstring 0}} {
    set result {}
    if {[llength $dictionaryOrValue] <= 1} {
        if {[string is integer $dictionaryOrValue] || \
                [string is double $dictionaryOrValue]} {
        # Number.
        if { $allstring } {
        set result "\"$dictionaryOrValue\""
        } else {
        set result $dictionaryOrValue
        }
        } else {
            # String.
            set result "\"$dictionaryOrValue\""
        }
    } else {
        # Dict.
        set allNumeric 1

        if {$numberDictArrays} {
            set values {}
            set i 0
            foreach {key value} $dictionaryOrValue {
                set allNumeric [expr {$allNumeric && ($key == $i)}]
                if {!$allNumeric} {
                    break
                }
                lappend values $value
                incr i
            }
        }

        if {$numberDictArrays && $allNumeric} {
            # Produce array.
            set arrayElements {}
            foreach x $values {
                lappend arrayElements [::json::stringify $x 1 $allstring]
            }
            set result "\[[join $arrayElements {, }]\]"
        } else {
            # Produce object.
            set objectDict {}
            foreach {key value} $dictionaryOrValue {
        foreach {k type} [split $key "!"] break
        if { $type eq "string" } {
            lappend objectDict "\"$k\": [::json::stringify $value 0 1]"
        } else {
            lappend objectDict "\"$k\": [::json::stringify $value 0 $allstring]"
        }
            }
            set result "{[join $objectDict {, }]}"
        }
    }
    return $result
}
```

**Comment by dbohdan** [comment]
I like the idea. Being able to enforce a particular serialization type for a Tcl value would definitely be useful for accessing typed external APIs. However, I'm not so sure about this particular approach. "In-band messaging" like "key!string" is compact but rather error-prone (what if you have a key with an "!" in it?) and you won't be able to write a corresponding `::json::parse` proc that decodes JSON to the same format unambiguously.

If you have the time I'd suggest you look into implementing one of the the following designs instead.

## Separate schema

You could rewrite `::json::stringify` as

``` Tcl
proc ::json::stringify {dictionaryOrValue {numberDictArrays 1} {schema {}}} {
    #...
}
```

where `schema` is a data structure mirroring the one you're trying to encode except that it contains value _types_ instead of the values themselves. Per the JSON spec the simple values' types would be "string", "number", "boolean" and "null". Arrays and objects would be expressed as Tcl dictionaries.

For

``` Tcl
::json::stringify {
    a 123
    b 123
    c {0 123 1 456}
    d true
    e true
    f null
    g null
} 1 {
    a string
    b number
    c {0 number 1 string}
    d string
    e boolean
    f string
    g null
}
```

the output would be

``` JSON
{
  "a": "123",
  "b": 123,
  "c": [123, "456"],
  "d": "true",
  "e": true,
  "f": "null",
  "g": null
}
```

## Type-follows-value schema

Alternatively, you could implement

``` Tcl
proc ::json::stringify {dictionaryOrValue {numberDictArrays 1} {schema 0}} {
    #...
}
```

where when `schema` is 1 a value type must follow every simple value. I.e., you'd write

``` Tcl
::json::stringify {
    a 123 string 
    b 123 number
    c {0 123 number 1 456 number}
    d true string
    e true boolean
    f null string
    g null null
} 1 1
```

to get the same output as above. 

This is similar to, but IMO more readable than, the [huddle](http://docs.activestate.com/activetcl/8.6/tcllib/yaml/huddle.html) format used by Tcllib's YAML encoder/decoder.

**Comment by efrecon** [comment]
You describe ideas similar to the ones that I had. I discarded them because I was lacking the time and was willing a quick fix. This is basically why I formulated my request the way I did.

I like both ideas. However, I think that Tcl does a pretty good job at guessing the type in most cases. So what about the following instead.

# formatting sugar

The last argument to stringify is a list of field matching patterns and type specification. The field matching patterns are tested against the whole hierarchy. If, during the traversal, a fully qualified field name matches the pattern, the type from the specification is used. Otherwise, stringify tries to do its best, pretty much as now. Patterns are `glob` style (to be quickly matched using `string match`) and tested against the fully qualified hierarchy. So a specification list would be:

```
a string c.* number d string
```

Instead of using the `.` to separate, we could also have sublists such as follows:

```
a string {c *} number d string
```

So to wrap it up:

```
::json::stringify {
    a 123
    b 123
    c {0 123 1 456}
    d true
    e true
} 1 {
    a string
    {c *} number
    d string
}
```

Would return

```
{
  "a": "123",
  "b": 123,
  "c": [123, 456],
  "d": "true",
  "e": true
}
```

There are pros and cons to all approaches. Mine relies on trusting that the default does a pretty good job at guessing and only provides help whenever needed. Your solutions are more strict and entirely self-contained.

I prefer mine because it is less verbose, but will also work when the "schema" changes in the data, but when you haven't had time to update the code, i.e. if there is suddenly a field `z` in the JSON that is not covered by the scheme specification.

Further thoughts?

(Maybe an hybrid solution??)

**Comment by dbohdan** [comment]
Interesting. With the dot notation there is again potential for ambiguity, so you'd have to implement quoting/escaping rules (for when you want to encode a key name with a dot in it). I think that is best avoided by simply using the Tcl list as path notation, i.e., `{a  b c}` to refer to the value 5 in `{"a": {"b": {"c": 5}}}` and `{d 1}` to refer to "bar" in  `{"d": ["foo", "bar"]}`.

One benefit of using lists would the ability to specify glob patterns unambiguously in the middle of a fully qualified name, e.g., `{orders * shipped} boolean` to declare as boolean the field "shipped" in all the orders in

```
{
  "orders": [
    {
      "id": 1,
      "shipped": true
      ...
    },
    {
      "id": 2,
      "shipped": false
      ...
    }
  ]
}
```

You could also introduce a special symbol like `**` to refer to all the subkeys at all levels in an object.

Overall, I think the solution you propose would work just fine.

As for a hybrid solution, I am not sure how it could be made to work. In its case `{a b c}` would have two incompatible meanings (`obj.a.b.c` and `obj['a b c']` in JavaScript notation). It would be awkward for the programmer to disambiguate between them.

One alternative solution I've thought of since our last exchange is a shorthand for lists like `c numbers` or `c list-of-numbers`. What I see as good about it is the simplicity but it offers no way to express `{orders * shipped} boolean`. The solution you propose is more powerful.

**Comment by efrecon** [comment]
Agreed for the dot notation, this is how my examples was actually using lists. I wanted to open the option and let you decide as you are the author of the library.

To be frank, I don't know if I have the time for an implementation right now, but we'll see. If you are up to the task... I'll keep you posted if I start on anything so we can join forces.

**Comment by dbohdan** [comment]
Now that you've put the idea in my head it's very likely I'll try and implement it :-). However, like you I have other priorities right now, so it may take a while before I do. Doing this properly would require some time to experiment, write tests, add an example to `examples.tcl` and so on. If you submit an implementation of your list-based schema (we need a more catchy name for it!) before me I will code review, test and merge it in jimhttp.

I'll be glad to see more of your thoughts on the matter here either way. I think this is the kind of notation could be seriously useful for helping Tcl interact not just with JSON but with other serialization formats as well.

By the way, our discussion has inspired [aspect](http://wiki.tcl.tk/21336) to produce [his own implementation](http://wiki.tcl.tk/41175) (and now there is a circular link between that wiki page and here).

**Comment by dbohdan** [comment]
Today's commits implement schemas. This includes support for nested values, which have the format of `array:(element type)`/`object:(value type)`. For example, you `array:object:array:number` means an array of objects whose values are arrays of numbers. What is not implemented is going from whole collections to named elements, i.e., what the example notation `{orders * shipped} boolean` demonstrated. Doing such queries properly (handling contradictions and domain overlaps) would require implementing a query engine and building the JSON generator around it. I have decided that that goes beyond the scope of the current implementation. It is more of something to do for a compatibility-breaking version 2.0.

Here's a use example: 

``` Tcl
source json.tcl

puts [::json::stringify {
    a 123
    b 123
    c {0 123 1 456}
    d true
    e true
} 1 {
    a string
    c array:number
    d string
}]
```

Running it will generate the output `{"a": "123", "b": 123, "c": [123, 456], "d": "true", "e": true}` or, prettified, 

``` JSON
{
  "a": "123",
  "b": 123,
  "c": [
    123,
    456
  ],
  "d": "true",
  "e": true
}
```

Edit: Schemas also give the option of not using number-keyed dicts to represent JSON arrays. E.g.,

``` Tcl
source json.tcl

puts [::json::stringify {
    a 123
    b 123
    c {123 456}
    d true
    e true
} 0 {
    a string
    c array:number
    d string
}]
```

produces the same output as the first example.
